### ISSUE TITLE
Adding number to sliders in gene creation

### ISSUE THREAD

**Issue by Drconfused** [codingcats7/artbreeder-userscript#1]
Anyway to get the sliders in the gene creation section to have the -valuenow=# to show on the relevant slider as in the example pic?
![sliders idea gene creation](https://user-images.githubusercontent.com/17419385/125331745-9e977600-e305-11eb-90ce-04a4a062a1c9.png)

**Comment by codingcats7** [comment]
got it. just pushed the commit. it's in the editGeneCreationPage function
