### ISSUE TITLE
_Animation ui change request.

### ISSUE THREAD

**Issue by Drconfused** [codingcats7/artbreeder-userscript#2]
In the animation section the demo window of what is in there is set at width:256px height:256px and I change it a lot to a higher number. It would be fabulous if this was able to be set via the script.

And not sure how to format all the horizontal_scroll_container contents but it would be nice if there were a toggle that allowed switching between vanilla size and a smaller size to see more pictures on screen.

**Comment by codingcats7** [comment]
I changed the demo window size :) Check out the styles in editAnimationPage(). 
As for the contents in horizontal_scroll_container, I'd recommend just using the browser zoom in/out to change their size ( in Chrome, Ctrl+ and Ctrl- are pretty convenient).

**Comment by Drconfused** [comment]
Superb.
I always use Crtrl and the scroll wheel to do zoom in and out. Why I would prefer having an independent function on the animation section to toggle is with the current zoom it makes every page like that and so using two monitors it would be nice to be able to keep the animations toggled to a zoom out without affecting the other pages.
