### ISSUE TITLE
Slider markings inquiry request.

### ISSUE THREAD

**Issue by Drconfused** [codingcats7/artbreeder-userscript#4]
Anyway to get markings at the 25, 50, 75% marks on the sliders especially in the areas that turning the sliders into numerics aren't used?

![Artbreeder_concept_ui_slider_markings2](https://user-images.githubusercontent.com/17419385/126044378-4adcbf20-27f3-4e6e-888c-292e72c211ca.png)

and in the Legacy: Mix-Images
![Artbreeder_concept_ui_slider_markings](https://user-images.githubusercontent.com/17419385/126044384-9c81c776-a3b9-48c9-8657-4116718b6afa.png)

**Comment by codingcats7** [comment]
Added in the most recent commit! I had to remove ArtBreeder's custom slider styling because it wouldn't let the tick-marks show for whatever reason (that's why they look so different now)
