### ISSUE TITLE
editAnimationPage height unfriendly for widescreen

### ISSUE THREAD

**Issue by Drconfused** [codingcats7/artbreeder-userscript#5]
At 100% view size on browser the preview image overlaps with the added images. 
I changed the width: 50vh to a 40 vh and that worked.

Is there an alternative method that is able to tell the resolution that adjusts according? or would it be having to have that value changed per user?

**Comment by codingcats7** [comment]
I'm using a pretty hi-res screen, so it's not surprising that something looks ok on my end but not on other devices. I did look into making it more responsive to different screens/sizes, but with the way things are done on the animation page I couldn't find a way to fix it without major CSS changes :( Anyway, I did update the value from 50vh to 40vh in the recent versions (it looks less blurry for me that way anyway).

**Comment by Drconfused** [comment]
It was really only an issue in the characters section because of the height being much greater than width.
